server:
  port: 22000

spring:
  application:
    name: order
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        # 注册地址，不需要写协议
        server-addr: 10.100.234.31:8848
        # 分组，不同分组之间不能调用，用于微服务之间的隔离
        group: DEFAULT_GROUP
        # 元数据，让配置更加灵活
        metadata:
          # 比如灰度发布时，可以跨集群调用，但是不能跨版本调用
          version: v1

management:
  # 加载 actuator 所有的端点（默认只加载 info / health）
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    # 允许关闭端点
    shutdown:
      enabled: true
    # 总是显示检查详细信息
    health:
      show-details: always
